name: Deploy App
on: [push]
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
    
     - name: Clone private repo
       run: git clone "https://violeta.iskandaryan:$EXTERNAL_TOKEN@git.toptal.com/raj/violeta.iskandaryan.git" main
       env:
         EXTERNAL_TOKEN : ${{ secrets.ACCESS_TOKEN }}
#       - name: Checkout private tools
#         uses: actions/checkout@master
#         with:
#           repository: raj/violeta.iskandaryan.git
#           token: ${{ secrets.ACCESS_TOKEN }}
