name: Deploy App
on: [push]
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
    
     - name: Clone Infrastructure Code
       run: git clone "https://violeta.iskandaryan:$EXTERNAL_TOKEN@git.toptal.com/raj/violeta.iskandaryan.git" main
       env:
         EXTERNAL_TOKEN : ${{ secrets.ACCESS_TOKEN }}
    
     - name: Clone Application
       run: git clone "https://violeta.iskandaryan:$EXTERNAL_TOKEN@git.toptal.com/henrique/node-3tier-app2" main/node-3tier-app2
       env:
         EXTERNAL_TOKEN : ${{ secrets.ACCESS_TOKEN }}
         
         
     - name: Build API ami
       uses: ExitoLab/packer_build_action_aws@v0.2.10
       with:
        templateFile: 'api.json'
        workingDir: 'main/base'
       env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
          
     - name: Build WEB ami
       uses: ExitoLab/packer_build_action_aws@v0.2.10
       with:
        templateFile: 'web.json'
        workingDir: 'main/base'
       env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
        
     - name: Install Terraform
       env:
        TERRAFORM_VERSION: "0.13.7"
       run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        
     - name: working dir
       run: ls -l
        
     - name: Verify Terraform version
       run: terraform --version

     - name: Terraform init
       working-directory: main/infra
       env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       run: terraform init -input=false

     - name: Terraform validation
       working-directory: main/infra
       run: terraform validate

     - name: Terraform apply
       working-directory: main/infra
       env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       run: terraform apply -auto-approve -input=false
# DEPLOY
