name: Deploy App
on: [push]
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
    
     - name: Clone private repo
       run: git clone "https://violeta.iskandaryan:$EXTERNAL_TOKEN@git.toptal.com/raj/violeta.iskandaryan.git" main
       env:
         EXTERNAL_TOKEN : ${{ secrets.ACCESS_TOKEN }}
         
     - name: workind dir
       run: cd main/node-3tier-app2 && ls -l
         
     - name: Build API ami
       uses: ExitoLab/packer_build_action_aws@v0.2.10
       with:
        templateFile: 'api.json'
        workingDir: 'main/base'
       env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
